name: craftapi
version: "1.0-SNAPSHOT"
author: Hitokii
main: dev.hitokii.craftapi.Main

commands:
  stopserver:
    description: Stops the server
    usage: /<command>
  startserver:
    description: Starts the server
    usage: /<command>
  registerchest:
    description: Registers a chest
    usage: /<command> <chestname>